### ISSUE TITLE
The method getStatePositionNumber(String) is undefined for the type Object

### ISSUE THREAD

**Issue by yichun463** [jdeschamps/EMU#19]
Hi
I met a new error recently:
After following the 23th step in the tutorial, this error is encountered.
![image](https://user-images.githubusercontent.com/66891774/98887134-5a32ac80-24d0-11eb-8517-588a6215ed1a.png)
And there' s no 'import' quick fix option.
![image](https://user-images.githubusercontent.com/66891774/98887125-4f781780-24d0-11eb-9e5e-0de83a718ab3.png)
While other places are proper.
Best wishes.

**Comment by jdeschamps** [comment]
"getStatePositionNumber" is a method defined in MultiStateUIProperty objects. Yet here, you are casting the UIProperty to Object. Therefore, as far as the compiler is concerned, there is not getStatePositionNumber method. This is why Eclipse is suggesting to "change method receiver cast", what happens if you click on that? It might fix it by casting the Object to the right Class.

If you look at the code shown in the tutorial, the UIProperty (returned by getUIProperty) is casted to a MultiStateUIProperty, in order to be able to call getStatePositionNumber.
```java
pos = ((MultiStateUIProperty)getUIProperty(FW_POSITION))
                .getStatePositionNumber(newvalue);
```

Why is it a MultiStateUIProperty in the tutorial? Because it is declared as such in the initializeProperties method. Check the [source code of the tutorial](https://github.com/jdeschamps/EMU-guide/tree/master/tutorial/src/main/java/com/myname/myui) when something seems to go wrong in your code.

Hope it made it clearer! Since this is more of a Java question than an issue with EMU, and that the answer is in the tutorial code snippets, I will close it now.
